### ISSUE TITLE
Issue with AES 256 encryption 

### ISSUE THREAD

**Issue by IslamHelmy** [ATaylorCEngFIET/MicroZed-Chronicles#1]
Dear Adam,

I am now trying the same algorithm you have posted for AES256 (and running it on SDSoC) but it seems for me the algorithm is not outputting a valid cipher text, based on your code implementation 
Data (which is state_temp) is equal to {0x00,0x44,0x88,0xcc,0x11,0x55,0x99,0xdd,0x22,0x66,0xaa,0xee,0x33,0x77,0xbb,0xff};
Initial Key:
uint8_t key[32] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
		0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f};  // initial key

Then the output cipher is:
8e 51 ea 4b a2 67 fc 49 b7 45 49 60 ca bf 90 89

However when i have checked the expected cipher at [https://csrc.nist.gov/csrc/media/publications/fips/197/final/documents/fips-197.pdf](url) and according to this aes calculator [https://www.hanewin.net/encrypt/aes/aes-test.htm](url) it shows a cipher text of 
07 5c ca 40 2d c1 fc 17 ec b9 9a 04 33 9f f4 8d
any help why is this happening ?

**Comment by ATaylorCEngFIET** [comment]
Hi I will look into this more tomorrow as it is late in the UK now however on first glance the results outlined in  https://forums.xilinx.com/t5/Xcell-Daily-Blog/Adam-Taylor-s-MicroZed-Chronicles-Part-97-SDSoC-In-depth-Example/ba-p/650465 which gives 8e 51 ea 4b a2 67 fc 49 b7 45 49 60 ca bf 90 89 as the output Cipher corresponds with the output given on page 47 of http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.197.pdf 

It is not explicitly stated but the input and output are in the 4 by 4 cofiguratio, which requires a little mental gymnastics

**Comment by IslamHelmy** [comment]
Thanks Adam for your comment ,
now this is more clear for me why it looks like that because of the 4*4 configuration, thanks
